#!/bin/bash

read -p "Enter a number:" num1
read -p "Enter a number:" num2

if ! [[ "$num" =~ ^-?[0-9]+$ ]];then
    echo " please enter a valid number"
    exit 1;
fi

if [ "$num1" gt "$num2" ]; then 
    echo " $num1 is gretaer than $num2"
else
    echo "$num2 is greater than $num1"
fi