#!/bin/bash

read -p "Enter a number:" num

if ! [[ "$num" =~ ^-?[0-9]+$ ]];then
    echo " please enter a valid number"
    exit 1;
fi
if [ "$num/2" -eq 1 ]; then 
    echo "the given number $num is odd number"
else
    echo "the given number $num is even number"
fi
